name: build matrix eggs

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # By default, GitHub will maximize the number of jobs run in parallel
      # depending on the available runners on GitHub-hosted virtual machines.
      # max-parallel: 8
      fail-fast: false
      matrix:
        include:
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"
          - python-version: "3.11"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python build
        run: |
          echo "Python ${{ matrix.python-version }}"
          python --version
          PYTHON_VERSION=${{ matrix.python-version }} ./build-all.sh
          ls -alh out
          ls -alh out/dist

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            out/dist
